### ISSUE TITLE
sympy doesn't interpret all strings as variables

### ISSUE THREAD

**Issue by Legotier** [LKlinke/Prodigy#14]
Certain strings are not interpreted as variables by sympy. An example for this is the string `sum`, which is interpreted as python's built-in sum function. This means that pgcl programs with a variable of this name cannot be interpreted correctly.

Commit e753cf744686bb26515b2ac1b2c2e2e9160c3a53 fixes this to some degree. Parameters still cannot have any of these names, and for variables to have such a name, they need to be explicitly defined in the `__init__` function of the GF. Also, there are likely more functions in the GF class that have this problem.

**Comment by Legotier** [comment]
Each remaining call to `sympy.S` should be passes an appropriate `locals` parameter, similar to `__init__`

**Comment by LKlinke** [comment]
this issue is of minor priority. We are aware of "bad" names for variables but this can easily avoided by a user renaming the program vars.

More important is a stable working version for updates etc. where the user does not have any influence on.
