### ISSUE TITLE
Fast generating function doesn't seem to be correct in all examples

### ISSUE THREAD

**Issue by Legotier** [LKlinke/Prodigy#15]
In the `burgler_alarm` example, with input distribution `1`, Prodigy computes the (simplified) result `called*maryWakes*phoneWorking*(280*alarm*burglary*earthquake + 2969703*alarm*burglary + 69930*earthquake + 988911099)/1549923456250000000000000000`. This doesn't seem to be correct, as the sum of the coefficients is not equal to one.

In contrast, using sympy, we get `called*maryWakes*phoneWorking*(280*alarm*burglary*earthquake + 2969703*alarm*burglary + 279720*alarm*earthquake + 988911099)/992160802`. Here, the coefficients sum up to one.

**Comment by Legotier** [comment]
The new update function computes the correct result, the old one is still incorrect though

**Comment by LKlinke** [comment]
is this still alive?

**Comment by Legotier** [comment]
> is this still alive?

This bug doesn't exist anymore in Prodigy. However, the old update function (which we don't use anymore) still exists in the GiNaC bindings. It should probably be deleted.

**Comment by LKlinke** [comment]
then please do either of the following: (1) open an issue in the bindings repo with this topic or (2) remove the bad and unused code form the bindings and update the respective repository.

Afterwards close this issue.
