### ISSUE TITLE
Incomplete installation instructions

### ISSUE THREAD

**Issue by fzaiser** [LKlinke/Prodigy#20]
I followed the installation instructions in the README, but the installation failed because the following packages were missing: cmake, pkg-config, cln, ginac. It's probably a good idea to add these dependencies to the readme. My OS is Ubuntu 22.04.

**Comment by Legotier** [comment]
I updated the installation instructions in 29028fe5c51dfb67ce1d2fd934151d026960c71a. Does this cover all problems you ran into?

**Comment by fzaiser** [comment]
Yes, it does, thanks!
