### ISSUE TITLE
instruction_handler not aware of the need of functions

### ISSUE THREAD

**Issue by thtomate** [LKlinke/Prodigy#22]
```
  File "prodigy/analysis/instruction_handler.py", line 497, in _analyze_with_invariant
    prog = Program(declarations=[],
TypeError: Program.__init__() missing 1 required positional argument: 'functions'
```

This error appears when giving an invariant file during run, i. e., evaluating a while loop and than choosing the cli option to supply an invariant file live.

**Comment by Legotier** [comment]
Fixed by c7a0b4b3a29fd3b497a1fd5dbfb31f7d119a7f5d
