### ISSUE TITLE
Parameters and expected values

### ISSUE THREAD

**Issue by Legotier** [LKlinke/Prodigy#6]
It is currently not possible to calculate the expected value of an expression based on a GF if that expression contains parameters. For example, the following code results in an error, because Prodigy tries to compute the marginal for the symbols `x` and `p`, and `p` is a parameter:

```python
gf = GeneratingFunction("(1-p) + p*x", 'x')
assert gf.get_expected_value_of('p*x') == "p^2"
```

**Comment by LKlinke** [comment]
Just to be on the same side, the result should be:
```latex
E[p * X] = p * E[X]
```
do you think you can implement this behaviour?

**Comment by Legotier** [comment]
I can definitely give it a try, I'll ask if I get stuck

**Comment by Legotier** [comment]
What should be the expected value of an expression that doesn't contain any variables (e.g. $E[3]$)? Right now we just return the same expression (i.e. $E[3] = 3$).

**Comment by LKlinke** [comment]
That is the correct behaviour.
